---
- hosts: all
  roles:
  become: true
  tasks:

  - name: install python3 package
    apt:
      name: python3
    when: ansible_distribution == "Ubuntu"

  - name: pip install package
    apt:
      name: pip
    when: ansible_distribution == "Ubuntu"

  - name: install java open-jdk
    apt:
      name: openjdk-8-jdk
    when: ansible_distribution == "Ubuntu"
